"""empty message

Revision ID: 4aca821f1c61
Revises: f471bb027028
Create Date: 2024-09-03 10:37:32.763861

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4aca821f1c61'
down_revision = 'f471bb027028'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('post_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('deliverer_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('main_content', sa.Text(), nullable=True),
    sa.Column('subject_tag', sa.String(length=100), nullable=True),
    sa.Column('language_tag', sa.String(length=100), nullable=True),
    sa.Column('mainpoint_tag', sa.String(length=100), nullable=True),
    sa.Column('deliver_time', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['deliverer_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('post_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    # ### end Alembic commands ###
