"""empty message

Revision ID: 58076d35c569
Revises: 4aca821f1c61
Create Date: 2024-09-03 11:21:15.190463

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '58076d35c569'
down_revision = '4aca821f1c61'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('deliver_time',
               existing_type=mysql.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.alter_column('deliver_time',
               existing_type=sa.DateTime(),
               type_=mysql.INTEGER(),
               existing_nullable=False)

    # ### end Alembic commands ###
