"""empty message

Revision ID: e15574466b64
Revises: 58076d35c569
Create Date: 2024-09-04 00:01:17.266220

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e15574466b64'
down_revision = '58076d35c569'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_img_path', sa.String(length=100), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar_path', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar_path')

    with op.batch_alter_table('blog', schema=None) as batch_op:
        batch_op.drop_column('cover_img_path')

    # ### end Alembic commands ###
